# Configuration file for Modular AmiBroker Trading System
# All default values are explicitly defined here

# Data source configuration
data:
  amibroker_path: "C:\\Users\\skyeAM\\OneDrive - Verona Capital\\Documents\\ABDatabase\\OneModel5MinDataABDB_1"
  data_frequency: "1T"                    # Data frequency (5T = 5 minutes)
  

# Backtesting configuration
backtest:
  # Portfolio settings
  initial_cash: 100000                    # Starting cash amount in dollars
  position_size: 1                        # Position size per trade ($1 for clean percentage/dollar relationship)
  position_size_type: "value"             # Size type: "value" (dollars), "amount" (shares), "percent" (% of portfolio)
  
  # VectorBT Pro execution timing settings
  signal_lag: 2                           # Bars to lag signals - VectorBT Pro native support
                                          # 0 = same bar execution (best-case)
                                          # 1 = next bar execution (realistic)
                                          # 2+ = multi-bar delay (conservative)

  # VectorBT Pro execution pricing options
  # Native options: "close", "open", "high", "low", "nextopen", "nextclose"
  # Custom formulas: "(H+L+C)/3" (typical), "(H+L)/2" (median), "hlc3" (built-in typical)
  # Advanced: Custom price arrays can be calculated and passed to execution engine
  execution_price: "close"                    # VectorBT Pro native price option

  # Legacy formula-based execution pricing (for non-VectorBT engines)
  # Common formulas: "C" (close), "(H+L+C)/3" (typical), "(H+L)/2" (median), "H" (high), "L" (low)
  buy_execution_formula: "(H + L + C) / 3"    # Formula for buy signals (long entries, short exits)
  sell_execution_formula: "(H + L + C) / 3"   # Formula for sell signals (long exits, short entries)
  
  # VectorBT Pro friction costs - applied to each trade
  fees: 0.000                             # Percentage commission on trade value (0.001 = 0.1% of trade size)
  fixed_fees: 0.0                         # Fixed dollar commission per trade (e.g., $1.00 per trade)
  slippage: 0.0000                        # Percentage slippage on entry/exit price (0.0005 = 0.05% of price)
  
  # Portfolio settings
  direction: "both"                       # Trade direction: "long", "short", or "both"
  min_size: 0.0000000001                 # Minimum position size for granularity (1e-10)
  call_seq: "auto"                        # VectorBT call sequence: "auto" or "reverse"
  freq: "5T"                             # Data frequency for VectorBT (should match data_frequency)
  
# Peak detection settings (if used by strategies)
peak_detection:
  min_time_stop: 1                        # Minimum bars for time-based stops
  max_time_stop: 100                      # Maximum bars for time-based stops
  
# Output configuration
output:
  results_dir: "results"                  # Directory to save backtest results
  trade_list_filename: "tradelist.csv"   # Filename for trade list export
  equity_curve_filename: "equity_curve.csv"  # Filename for equity curve export
  performance_filename: "performance_summary.csv"  # Filename for performance metrics
  
# System settings
system:
  random_seed: 42                         # Random seed for reproducible results (null for random)
  max_workers: null                       # Maximum parallel workers (null = auto-detect)
  memory_limit: null                      # Memory limit in GB (null = no limit)

# Execution engine configuration
use_unified_engine: true                 # Enable unified execution engine (false = use legacy path)
use_pure_array_processing: true          # Use O(1) pure array processing engine (false = use O(n) legacy engine)

# Phased Entry Configuration (Pyramid/Scaling Strategies) - VectorBT Pro Integration
phased_entries:
  enabled: false                          # Enable phased/pyramid entries
  max_phases: 3                          # Maximum number of phases per position
  initial_size_percent: 40.0             # Percentage of total position for first phase

  # VectorBT Pro Execution Method
  execution_method: "volume"              # "volume", "time", or "hybrid"
  use_vectorbt_accumulate: true           # Use VectorBT Pro native accumulate=True feature

  # Volume-Based Phasing (VWAP/Liquidity Execution)
  volume_based:
    target_participation: 0.10            # Target % of average volume per phase (10% = conservative)
    min_volume_threshold: 1000            # Minimum volume required per bar to execute
    max_bars_per_phase: 20                # Maximum bars to complete one phase
    volume_lookback: 20                   # Bars to calculate average volume
    use_vwap_pricing: true                # Use VWAP over execution period

  # Time-Based Phasing (TWAP Execution)
  time_based:
    phase_interval_bars: 5                # Bars between each phase entry
    max_total_time_bars: 50               # Maximum total bars to complete all phases
    use_twap_pricing: true                # Use TWAP over execution period

  # Hybrid Method (Volume + Time Constraints)
  hybrid:
    prefer_volume: true                   # Prioritize volume over time constraints
    volume_timeout_bars: 10               # Switch to time-based if volume unavailable
    time_fallback: true                   # Fall back to time-based if volume insufficient

  # Phase Trigger Configuration (Traditional - for non-VectorBT execution)
  phase_trigger:
    type: "percent"                      # Trigger type: "percent", "points", "atr_multiple"
    value: 1.5                           # Trigger value (1.5% move in favor for next phase)

  # Phase Size Configuration
  phase_sizing:
    type: "equal"                        # Size type: "equal", "decreasing", "increasing", "custom"
    multiplier: 1.0                      # Multiplier for non-equal sizing
    custom_ratios: [0.4, 0.35, 0.25]   # Custom phase size ratios (must sum to 1.0)

  # Risk Management
  risk_management:
    max_adverse_move: 3.0                # Stop scaling if adverse move exceeds this %
    require_profit: true                 # Only add phases when current position is profitable
    time_limit_bars: 50                  # Maximum bars to complete all phases
    max_slippage_percent: 1.0            # Maximum acceptable slippage per phase

  # Stop Loss Adaptation
  stop_loss:
    adapt_to_phases: true                # Adjust stop loss as phases are added
    use_average_price: true              # Base stop loss on average entry price vs first entry